// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RacingTelemetryAnalyzer.Data;

#nullable disable

namespace RacingTelemetryAnalyzer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260829154959_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.AnalysisResult", b =>
                {
                    b.Property<int>("AnalysisResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalysisResultId"));

                    b.Property<double>("BrakingPercentage")
                        .HasColumnType("float");

                    b.Property<double>("EntrySpeed")
                        .HasColumnType("float");

                    b.Property<double>("ExitSpeed")
                        .HasColumnType("float");

                    b.Property<int>("LapId")
                        .HasColumnType("int");

                    b.Property<double>("MinimumSpeed")
                        .HasColumnType("float");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ThrottleResponseTime")
                        .HasColumnType("float");

                    b.Property<double>("TimeDelta")
                        .HasColumnType("float");

                    b.Property<int?>("TrackSectionId")
                        .HasColumnType("int");

                    b.HasKey("AnalysisResultId");

                    b.HasIndex("LapId");

                    b.HasIndex("TrackSectionId");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.Lap", b =>
                {
                    b.Property<int>("LapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LapId"));

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<int>("LapNumber")
                        .HasColumnType("int");

                    b.Property<long>("LapTime")
                        .HasColumnType("bigint");

                    b.Property<double>("Sector1Time")
                        .HasColumnType("float");

                    b.Property<double>("Sector2Time")
                        .HasColumnType("float");

                    b.Property<double>("Sector3Time")
                        .HasColumnType("float");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("LapId");

                    b.HasIndex("SessionId");

                    b.ToTable("Laps");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("TrackId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.SessionCondition", b =>
                {
                    b.Property<int>("SessionConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionConditionId"));

                    b.Property<double>("AirTemperature")
                        .HasColumnType("float");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("TrackCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TrackTemperature")
                        .HasColumnType("float");

                    b.Property<string>("Weather")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("float");

                    b.HasKey("SessionConditionId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("SessionConditions");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.SessionNote", b =>
                {
                    b.Property<int>("SessionNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionNoteId"));

                    b.Property<int?>("LapId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int?>("TrackSectionId")
                        .HasColumnType("int");

                    b.HasKey("SessionNoteId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionNotes");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.TelemetryPoint", b =>
                {
                    b.Property<int>("TelemetryPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TelemetryPointId"));

                    b.Property<double>("Brake")
                        .HasColumnType("float");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<double?>("FrontBrake")
                        .HasColumnType("float");

                    b.Property<double?>("FrontSuspension")
                        .HasColumnType("float");

                    b.Property<int>("Gear")
                        .HasColumnType("int");

                    b.Property<int>("LapId")
                        .HasColumnType("int");

                    b.Property<double?>("LeanAngle")
                        .HasColumnType("float");

                    b.Property<int>("RPM")
                        .HasColumnType("int");

                    b.Property<double?>("RearBrake")
                        .HasColumnType("float");

                    b.Property<double?>("RearSuspension")
                        .HasColumnType("float");

                    b.Property<int>("Sector")
                        .HasColumnType("int");

                    b.Property<double>("Speed")
                        .HasColumnType("float");

                    b.Property<double?>("Steering")
                        .HasColumnType("float");

                    b.Property<double?>("SuspensionFL")
                        .HasColumnType("float");

                    b.Property<double?>("SuspensionFR")
                        .HasColumnType("float");

                    b.Property<double?>("SuspensionRL")
                        .HasColumnType("float");

                    b.Property<double?>("SuspensionRR")
                        .HasColumnType("float");

                    b.Property<double>("Throttle")
                        .HasColumnType("float");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("TelemetryPointId");

                    b.HasIndex("LapId");

                    b.ToTable("TelemetryPoints");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfTurns")
                        .HasColumnType("int");

                    b.HasKey("TrackId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.TrackSection", b =>
                {
                    b.Property<int>("TrackSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackSectionId"));

                    b.Property<double>("EndDistance")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StartDistance")
                        .HasColumnType("float");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("TrackSectionId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackSections");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("TopSpeed")
                        .HasColumnType("int");

                    b.Property<int>("VehicleCategory")
                        .HasColumnType("int");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.VehicleSetup", b =>
                {
                    b.Property<int>("VehicleSetupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleSetupId"));

                    b.Property<double>("BrakeBias")
                        .HasColumnType("float");

                    b.Property<double>("FrontWing")
                        .HasColumnType("float");

                    b.Property<double>("RearWing")
                        .HasColumnType("float");

                    b.Property<double>("RideHeight")
                        .HasColumnType("float");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("VehicleSetupId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("VehicleSetups");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.AnalysisResult", b =>
                {
                    b.HasOne("RacingTelemetryAnalyzer.Models.Lap", "Lap")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("LapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RacingTelemetryAnalyzer.Models.TrackSection", "TrackSection")
                        .WithMany()
                        .HasForeignKey("TrackSectionId");

                    b.Navigation("Lap");

                    b.Navigation("TrackSection");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.Lap", b =>
                {
                    b.HasOne("RacingTelemetryAnalyzer.Models.Session", "Session")
                        .WithMany("Laps")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.Session", b =>
                {
                    b.HasOne("RacingTelemetryAnalyzer.Models.Track", "Track")
                        .WithMany("Sessions")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RacingTelemetryAnalyzer.Models.Vehicle", "Vehicle")
                        .WithMany("Sessions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.SessionCondition", b =>
                {
                    b.HasOne("RacingTelemetryAnalyzer.Models.Session", "Session")
                        .WithOne("Condition")
                        .HasForeignKey("RacingTelemetryAnalyzer.Models.SessionCondition", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.SessionNote", b =>
                {
                    b.HasOne("RacingTelemetryAnalyzer.Models.Session", "Session")
                        .WithMany("Notes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.TelemetryPoint", b =>
                {
                    b.HasOne("RacingTelemetryAnalyzer.Models.Lap", "Lap")
                        .WithMany("TelemetryPoints")
                        .HasForeignKey("LapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lap");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.TrackSection", b =>
                {
                    b.HasOne("RacingTelemetryAnalyzer.Models.Track", "Track")
                        .WithMany("Sections")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.VehicleSetup", b =>
                {
                    b.HasOne("RacingTelemetryAnalyzer.Models.Session", "Session")
                        .WithOne("Setup")
                        .HasForeignKey("RacingTelemetryAnalyzer.Models.VehicleSetup", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.Lap", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("TelemetryPoints");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.Session", b =>
                {
                    b.Navigation("Condition")
                        .IsRequired();

                    b.Navigation("Laps");

                    b.Navigation("Notes");

                    b.Navigation("Setup")
                        .IsRequired();
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.Track", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("RacingTelemetryAnalyzer.Models.Vehicle", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
